### ISSUE TITLE
Exception in TA with new time calculation

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#102]
When the first "ADAPTING" message is sent from rainbow, the TA throws the following error:

```
cp3_ta    |   File "/usr/src/app/swagger_server/controllers/default_controller.py", line 103, in internal_status_post
cp3_ta    |     update="ADAPTING")
cp3_ta    |   File "/usr/src/app/swagger_server/controllers/default_controller.py", line 38, in track_adapt
cp3_ta    |     config.time_spent_adapting = config.time_spent_adapting + (t_now - config.time_at_last_adapt)
cp3_ta    | TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by schmerl** [comment]
This is blocking me.

**Comment by ivoysey** [comment]
This should be fixed by https://github.mit.edu/brass/cmu-robotics/commit/7a4f41e5274dc6215eb04028fb9f2ebbe656cc0d -- it was an initial conditions problem, the first time we get an adapt message, we don't have a time for the most recent previous one yet, so we can't update the sum-so-far in the same way.
