### ISSUE TITLE
Implement dummy THs for internal testing

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#44]
Our internal testing is hampered because we do not have a TH, which needs to be in place for the TA to actually work.

We need to take the swagger files and generate a dummy TH that can at least get us to the started state so that we can start tests and test TA semantics and coordination with the back end.

**Comment by pooyanjamshidi** [comment]
For internal testing, I think, we only need a TA. I guess we can generate a dummy TA from the swagger file you generated for cp1 and other cps, right @ivoysey?

**Comment by ivoysey** [comment]
@pooyanjamshidi no, bradley is right, we need the TH. To see why, just look at any of the sequence diagrams: the first thing the TA does is send a request to the `TH:/ready` for the initial configuration data. If that request fails, the only thing that can happen is that the whole test fails -- so no TH means no configuration means failure.

We specifically don't need to generate a dummy TA because the deliverable we're working on is exactly a non-dummy TA.

The thing that we can do is generate a TH stub from the swagger spec we have for it and hard code in some specific testing behavior so that at least the TA's calls to the TH don't just fail immediately. I believe @ChrisTimperley has some ideas for how to do that for CP2 fairly quickly, for example.

**Comment by pooyanjamshidi** [comment]
We can simply put a default configuration hardcoded in a dumb TH, something like:
```json
{
  "discharge-budget": 10,
  "level": "a",
  "power-model": 0,
  "start-loc": "l1",
  "target-locs": ["l2", "l4", "l2", "l5", "l8"]
}
```
then there is no failure ;)

**Comment by ivoysey** [comment]
Yes. Or make it read from a file so it's a little bit easier to change.

**Comment by ivoysey** [comment]
I'm moving this to RR2 IW.

**Comment by schmerl** [comment]
This is related to: #72
