### ISSUE TITLE
Work out reasonable discharge coefficients for CP3

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#51]
The numbers should roughly follow these constraints:

headlamp < lidar < kinect < camera

**Comment by bisc** [comment]
Could you put a pointer here to the simulation code that we reviewed today?

**Comment by schmerl** [comment]
https://github.com/cmu-mars/brass_gazebo_plugins/blob/develop/src/energy_monitor.cc

**Comment by bisc** [comment]
I drafted the new power model for CP3 here: https://docs.google.com/document/d/1QlShodvDUHOKNkLmW1OlruyOCmAZ1_zaHC9v9LujWkI

It was pretty easy to satisfy the camera > kinect constraint. But the other two are a mess: 
- the newest most-minimal LIDAR puck consumes 50% more energy than kinect (and 50% less than the camera). Other, more standard lidars are even more power-consuming. Can less we rethink this constraint? 
- the expectation to have the headlamp consume less than any of these devices is _wild_. The one I found (roughly would produce a similarly strong light as I saw in the simulation) consumes **10-50x** the other devices. One can play around and find weaker lamps, but overall it's an unrealistic expectation. I think we have to rethink this constraint.

Otherwise, the model is ready to be incorporated into the planner and the simulator.

**Comment by schmerl** [comment]
Hmm. maybe I miscommunicated the constraints because I think headlamp
should be expensive and lidar too. I would expect camera to be less than
Kinect seeing that Kinect has camera.

**Comment by bisc** [comment]
Oh haha, I read the less-than signs literally. 

I've put in a less ambitious camera, now the relation is as specified.

**Comment by ivoysey** [comment]
@bisc what's up with this issue?

**Comment by bisc** [comment]
I think it's done.

**Comment by schmerl** [comment]
Need to church with Javier.
