### ISSUE TITLE
Implement CollisionData collector

### ISSUE THREAD

**Issue by schmerl** [cmu-mars/issues#73]

**Comment by schmerl** [comment]
I have implemented this in `cp3.py` with an example in `cli.py`. The following lines give examples of how to use this:

```
bump_events = []
def bump_record(bumped, velocity, time):
    bump_events.append({"bumped" : bumped, "velocity" : velocity, "time" : time})
cp.track_bumps(bump_record)
```
After the mission, the bump_events will contain the data. This needs to be turned into `CollisionData`.

**Comment by ivoysey** [comment]
I've implemented this now in https://github.mit.edu/brass/cmu-robotics/commit/6bd6502f79250166c088b57245c5120da9e9fd5f

@schmerl two questions for you:

1. the first argument, bumped, seems to be always `True` in `cp3.py`, so I'm ignoring it. 
2. `CollisionData` also includes a coordinate pair of where the bot was when it bumped, which you don't pass to the callback. I'm producing them by asking Gazebo where the robot is when the callback gets called; I'm a little worried that there could be some hard to predict lag in there and we'll get inaccurate coordinates. A possible solution would be to change the callback to also get the coordinates and then report those, which would remove one or two steps in the process.

If both of these are OK with you, I'm good with closing this issue; otherwise let me know what you want to do.

**Comment by ivoysey** [comment]
Whoops -- I meant https://github.mit.edu/brass/cmu-robotics/commit/6bd6502f79250166c088b57245c5120da9e9fd5f not the merge commit after it; fixed above, including here incase you're using email.

**Comment by ivoysey** [comment]
Closing this per discussion in Slack.
