### ISSUE TITLE
Making planner more intelligent to remember where the obstacle was

### ISSUE THREAD

**Issue by pooyanjamshidi** [cmu-mars/issues#96]
So that in cases that the obstacle where the robot does not go to a corridor that at the end of it sees the obstacle again and again. This is something we need to discuss with @javier-camara and probably we need to give some probably that the obstacle may be removed. So this intelligence is good for our secondary criteria, which is timeliness.

**Comment by javier-camara** [comment]
I am not sure I understand the problem. @schmerl , correct me if I am wrong, but I believe that if an obstacle is found, the IG fails, the corresponding edge in the map model is removed, a new waypoint with the location of the robot is inserted, and the robot replans an alternative route, so the knowledge about the obstacle being there is already (implicitly) represented in the model, right?

**Comment by javier-camara** [comment]
OK, forget what I said. I have realized that you might be talking about carrying out that information across the execution of subsequent tasks. Is that the case? If so, we can certainly discuss it, although it is not a trivial change.

**Comment by pooyanjamshidi** [comment]
@javier-camara yes, because I saw a case where the robot went through the same corridor where the obstacle was, see my comment in #84.

**Comment by schmerl** [comment]
Say we have a mission that has l2, l4, l2
1. We place an obstacle between l2 and l4 
2. When the mission sequencer starts the mission, it will give the path l2, l4 thinking there is no obstacle
3. The robot stops because of obstacle
4. Rainbow notices this and issues alternate plan for l2->l4 avoiding obstacle
5. Robot gets to l4
6. Rainbow tells mission sequencer task is done
7. Mission sequencer issues new instructions for l4->l2

Note, the mission sequencer will issue the IG for l4->l2 blissfully unaware of the obstacle. If the Rainbow planner is invoked somewhere along the way, it remembers that the old obstacle is there, but that won't have an affect on that path until Rainbow is called.

**Comment by pooyanjamshidi** [comment]
So if I understood this scenario correctly, we need to figure out how make rainbow to carry knowledge across tasks?

**Comment by schmerl** [comment]
No, rainbow already does that. The "issue" which is really a consequence of the design of the problem is in step 7.

**Comment by pooyanjamshidi** [comment]
But it has to go to `l2` that's the mission specification.

**Comment by schmerl** [comment]
That's a separate issue. It is trying to go to l2 but the second time the
obstacle is encountered, there was a bug in rainbow where the planner
wasn't invoked a second time. This is the fix I checked in this morning
that I think we're still trying to work out -- the current state is that
the new plan gives a speed of -0.04 which is a problem with the learner(?)
that you're currently fixing.

**Comment by pooyanjamshidi** [comment]
Speed issue is now fixed, so closing this issue.
